preset: full
system:
  topology: ../../data/bpti_shaw/bpti-protein.pdb
  trajectories:
  - ../../data/bpti_shaw/bpti-protein-001.dcd
  - ../../data/bpti_shaw/bpti-protein-002.dcd
  - ../../data/bpti_shaw/bpti-protein-003.dcd
  trajectory_names:
  - run1
  - run2
  - run3
  selection: protein
  align_selection: backbone
frames:
  start: 0
  stop: null
  step: 1
runtime:
  seed: 42
  resume: false
output:
  outdir: results
  figure_formats:
  - png
  - pdf
  dpi: 300
plot:
  publication_style: true
  timeseries_distribution: true
#  distribution_kind: hist_kde
  hist_bin_method: fd
  hist_bins: null
rmsd:
#  reference: ../data/pdbs/2YXJ.pdb
  map_mode: align
  selection: name CA
  align: true
  align_selection: protein and name CA
  debug_write_aligned_pdb: true
  debug_max_frames: 5
  region_mode: global
rmsf:
  selection: protein and name CA
  align: true
  align_to: average
  align_selection: protein and backbone
pca:
  mode: project
  fit_trajectory: run1
  align: true
  n_components: 3
  use_pcs: [1, 2, 3]
#  reference_pdbs:
#  - ../data/pdbs/2YXJ.pdb
#  reference_names:
#  - xtal_2YXJ
  free_energy_enabled: true
  free_energy_bins: auto_fd
  free_energy_level_step_rt: 0.2
  free_energy_smooth_sigma: 1.0
  free_energy_per_trajectory: false
#  site_from_reference_ligand: false
#  site_reference_pdb: ../data/pdbs/2YXJ.pdb
#  site_ligand_selection: resname N3C
#  site_cutoff: 5.0
#  site_atom_selection: name CA
#  site_align_selection: protein and name CA
#  site_map_mode: align
cluster:
  method: hdbscan
  min_cluster_size: 10
  representative_method: medoid
  allow_single_cluster: true
sasa:
  selection: protein
  level: residue
  probe_radius: 1.4
  relative: true
  reference_scale: tien2013
  rsasa_clip: false
dssp:
  selection: protein
  coil_code: C
distance:
  pairs:
  - id: active_site
    sel1: segid A and resid 45 and name CA
    sel2: segid A and resid 143 and name CA
ramachandran:
  mode: both
  selection: protein
  residues: [A:2, A:3]
analyses:
  distance: true
  ramachandran: true
  sasa: false
