preset: standard
system:
  topology: ../../data/WT/topology.pdb
  trajectories:
  - ../../data/WT/samples.xtc
  - ../../data/F143W/samples.xtc
  trajectory_names:
  - WT
  - F143W
  selection: protein
  align_selection: backbone
frames:
  start: 0
  stop: 1000
  step: 1
output:
  outdir: ./results_local
  figure_formats:
  - png
  - pdf
  dpi: 300
analyses:
  dssp: false
  ligand_site: false
  sasa: false
  distance: true
  ramachandran: false
rmsd:
  enabled: true
  reference: ../../data/pdbs/2YXJ.pdb
  map_mode: align
  selection: name CA
  align: true
  align_selection: protein and name CA
  region_mode: ligand_site
  ligand_selection: resname N3C
  site_cutoff: 5.0
  min_mapped: 10
  min_coverage: 0.2
  debug_write_aligned_pdb: true
  debug_max_frames: 5
rmsf:
  enabled: true
  selection: protein and name CA
  align: true
  align_to: average
  align_selection: protein and backbone
pca:
  enabled: true
  mode: project
  fit_trajectory: WT
  selection: backbone
  n_components: 5
  use_pcs:
  - 1
  - 2
  - 3
  reference_pdbs:
  - ../../data/pdbs/2YXJ.pdb
  reference_names:
  - xtal_2YXJ
  site_from_reference_ligand: true
  site_reference_pdb: ../../data/pdbs/2YXJ.pdb
  site_ligand_selection: resname N3C
  site_cutoff: 5.0
  site_atom_selection: name CA
  site_align_selection: protein and name CA
  site_map_mode: align
cluster:
  enabled: true
  min_cluster_size: 20
  representative_method: medoid
distance:
  enabled: true
  pairs:
  - id: ca_45_143
    sel1: protein and resid 45 and name CA
    sel2: protein and resid 143 and name CA
