preset: standard
system:
  topologies:
    - ../../data/WT/topology.pdb
    - ../../data/F143W/topology.pdb
  trajectories:
    - ../../data/WT/samples.xtc
    - ../../data/F143W/samples.xtc
  trajectory_names:
    - WT
    - F143W
  selection: protein
  align_selection: backbone
frames:
  start: 0
  stop: 1000
  step: 1
output:
  outdir: ./results_local
  figure_formats: [png, pdf]
  dpi: 300
analyses:
  dssp: true 
  sasa: true 
  distance: true
  ramachandran: true 
rmsd:
  reference: ../../data/pdbs/2YXJ.pdb
  map_mode: align
  selection: "name CA"
  align: true
  align_selection: "protein and name CA"
  region_mode: ligand_site
  ligand_selection: "resname N3C"
  site_cutoff: 5.0
  min_mapped: 10
  min_coverage: 0.2
  debug_write_aligned_pdb: true
  debug_max_frames: 1
  export_below_threshold: true
  threshold_angstrom: 1.5
  export_selection: "all"
  max_export_frames: 50
rmsf:
  selection: "protein and name CA"
  align: true
  align_to: average      # average | first
  align_selection: "protein and backbone"

pca:
  mode: project
  fit_trajectory: WT
  selection: backbone
  n_components: 5
  use_pcs: [1, 2, 3]
  reference_pdbs: [../../data/pdbs/2YXJ.pdb]
  reference_names: [xtal_2YXJ]
  site_from_reference_ligand: true
  site_reference_pdb: ../../data/pdbs/2YXJ.pdb
  site_ligand_selection: "resname N3C"
  site_cutoff: 5.0
  site_atom_selection: "name CA"
  site_align_selection: "protein and name CA"
  site_map_mode: align
  free_energy_bins: auto_fd
  free_energy_level_step_rt: 0.5
  free_energy_smooth_sigma: 0.5
cluster:
  min_cluster_size: 20
  allow_single_cluster: true
  representative_method: random
  representative_random_n: 5
  representative_random_seed: 7
distance:
  pairs:
    - id: ca_45_46
      sel1: "protein and resid 45 and name CA"
      sel2: "protein and resid 46 and name CA"
