preset: standard
system:
  topology: ../../data/WT/topology.pdb
  trajectories:
  - ../../data/WT/samples.xtc
  - ../../data/F143W/samples.xtc
  trajectory_names:
  - WT
  - F143W
  selection: protein
  align_selection: backbone
frames:
  start: 0
  stop: 1000
  step: 1
output:
  outdir: ./results_local
  figure_formats:
  - png
  - pdf
  dpi: 300
analyses:
  dssp: false
  sasa: false
  distance: true
  ramachandran: false
rmsd:
  atom_selection: name CA
  reference: ../../data/pdbs/2YXJ.pdb
  map_mode: strict
  alignment_selection: protein and name CA
  rmsd_selection: name CA
  superpose: true
  region_mode: ligand_site
  ligand_selection: not protein and not resname HOH and not resname SOL
  site_cutoff: 5.0
  min_mapped: 10
  min_coverage: 0.2
pca:
  mode: project
  fit_trajectory: WT
  selection: backbone
  n_components: 5
  use_pcs:
  - 1
  - 2
  - 3
  reference_pdbs:
  - ../../data/pdbs/2YXJ.pdb
  reference_names:
  - xtal_2YXJ
cluster:
  min_cluster_size: 20
  representative_method: medoid
distance:
  pairs:
  - id: ca_45_143
    sel1: protein and resid 45 and name CA
    sel2: protein and resid 143 and name CA
